---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-stock
  namespace: nautible-app-ms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nautible-app-ms-stock
        env:
        - name: QUARKUS_PROFILE
          value: aws-local-dev
        #- name: JAVA_VERSION
        #  value: "11"
