---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-stock
  namespace: nautible-app
spec:
  template:
    spec:
      containers:
      - name: nautible-app-stock
        image: public.ecr.aws/nautible/nautible-app-stock:52a15ca72509c709e7cd05591600fee1cc0f8ea5
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
