---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-stock
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-stock
        image: public.ecr.aws/nautible/nautible-app-ms-stock:20c827c2e059b8333e006fc81e6e5e53a26bce26
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
