apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: stock-pubsub
  namespace: nautible-app-ms
  labels:
    app.kubernetes.io/name: stock-pubsub
    app.kubernetes.io/instance: stock-pubsub
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: pubsub
    app.kubernetes.io/part-of: nautible
    app.kubernetes.io/managed-by: manual
spec:
  type: pubsub.snssqs
  version: v1
  metadata:
  - name: region
    value: us-east-1