---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-stock
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-stock
        image: public.ecr.aws/nautible/nautible-app-ms-stock:9416ff2eb334a41ca6f61887dd7cd225d55626ad
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
