---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-stock
  namespace: nautible-app
spec:
  template:
    spec:
      containers:
      - name: nautible-app-stock
        image: public.ecr.aws/nautible/nautible-app-stock:b979af6179cd0d8e58d38f7ff7e6a33dc40561d2
        env:
        - name: QUARKUS_PROFILE
          value: aws-dev
        - name: QUARKUS_DYNAMODB_AWS_REGION
          value: ap-northeast-1
