---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-stock
  namespace: nautible-app
spec:
  template:
    spec:
      containers:
      - name: nautible-app-stock
        image: nautibledevacr.azurecr.io/nautible-app-stock:52a15ca72509c709e7cd05591600fee1cc0f8ea5
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-cosmosdb
              key: DATABASE_PW
