---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nautible-app-ms-stock
  namespace: nautible-app-ms
spec:
  template:
    spec:
      containers:
      - name: nautible-app-ms-stock
        image: nautibledevacr.azurecr.io/nautible-app-ms-stock:83cf37e5f588f1dc29272ee78d23b6c9140c6e43
        env:
        - name: QUARKUS_PROFILE
          value: azure-dev
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_USER
        - name: DB_PW
          valueFrom:
            secretKeyRef:
              name: secret-nautible-app-ms-cosmosdb
              key: DATABASE_PW
